spring:
  security:
    oauth2:
      authorization-server:
        client:
          api-client:
            registration:
              client-id: api-client-id
              client-secret: "{noop}api123"
              client-authentication-methods: client_secret_basic
              authorization-grant-types: client_credentials
            token:
              access-token-time-to-live: 36000s